name: Generate Snake Animation

on:
  schedule: # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow pushing to output branch
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # Required for github-pages deploy

      - name: Generate Snake
        uses: Platane/snk@v3 # Use stable version
        with:
          github_user_name: mugishaprosper
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: '2E8B57'

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
